### ISSUE TITLE
Publish 1.0

### ISSUE THREAD

**Issue by matklad** [cuviper/autocfg#16]
This seems to be a really great foundational crate with a rather narrow and well defined API. Maybe just publish 1.0, while there are relatively few users, to avoid upgrade pains?

**Comment by cuviper** [comment]
I would be OK with that -- especially with #19 that will allow you to check pretty much anything. Would you care to review that, and maybe audit the API in general for 1.0? (Perhaps you already have...)

**Comment by matklad** [comment]
I've looked through the API surface of the crate, everything seems reasonable! The only two non super obvious bits were: 

* `rerun_path` and `rerun_env` names are not self-explanatory. `return_if_x_changed` would be more obvious at the call site, but it probably doesn't make sense to do a rename, as it's a really minor issue, the explicit version is significantly more verbose (though this shouldn't matter much for build scripts?), and we already have an existing API.

* `Error` type does not implement the new `Source` method, but it's not unclear how to support that, without some hockey bootstraping scheme for autocfg itself.

**Comment by matklad** [comment]
Oh, in Cargo.toml, `license = "Apache-2.0/MIT"` I think should be spelled as `license = "Apache-2.0 OR MIT"`, but I am not sure if Cargo 1.0 supports this.

**Comment by cuviper** [comment]
> * `rerun_path` and `rerun_env` names are not self-explanatory. `return_if_x_changed` would be more obvious at the call site, but it probably doesn't make sense to do a rename, as it's a really minor issue, the explicit version is significantly more verbose (though this shouldn't matter much for build scripts?), and we already have an existing API.

I see your point, but yes, the added verbosity would seem unfortunate. I think it's ok to excuse the terse names because the API surface is so small.

> * `Error` type does not implement the new `Source` method, but it's not unclear how to support that, without some hockey bootstraping scheme for autocfg itself.

Yeah, I think that bootstrap complexity would not be justified. I expect most cases will just be unwrapped anyway, so the `Debug` implementation is really what matters.

> Oh, in Cargo.toml, `license = "Apache-2.0/MIT"` I think should be spelled as `license = "Apache-2.0 OR MIT"`, but I am not sure if Cargo 1.0 supports this.

AFAICT Cargo doesn't validate the license at all, leaving it to the registry:
https://github.com/rust-lang/cargo/blob/7059559d71de3fffe8c8cb81e32f323454aa96c5/src/cargo/core/manifest.rs#L75-L79

**Comment by matklad** [comment]
Yeah, indeed, Cargo doesn’t do validation here. So, we should change this to OR, because that’s what standard says.

https://github.com/rust-lang/cargo/issues/2039

**Comment by cuviper** [comment]
Published!

**Comment by matklad** [comment]
@cuviper I think it might be the good idea to announce the crate on urlo/r/rust? I have a feeling that this crate is barely known (19 :star:, and I know it only because I was browsing cargo's issue tracker the other day and noticed alexcrichton mentioning it in passing). At the same time, I think there will be ecosystem-wide goodness if everyone converges to this crate.

Also, "MSRV is 1.0.0" is just to cool to not brag about :-)
