### ISSUE TITLE
crate has single crates.io owner

### ISSUE THREAD

**Issue by matklad** [cuviper/autocfg#23]
Hey, I've just noticed that this crate has only a single owner on crates.io. It might be a good idea to add a backup maintainer just in case.

**Comment by cuviper** [comment]
Yes... are you interested?

**Comment by matklad** [comment]
Yup, I can be a backup maintainer!

**Comment by cuviper** [comment]
OK, thanks! You should have invitations to both the repo and crates.io. Please close the issue when you've accepted those.
