### ISSUE TITLE
error: could not compile `autocfg`

### ISSUE THREAD

**Issue by crackfan** [cuviper/autocfg#37]
error: failed to build archive: function not supported

error: aborting due to previous error

error: could not compile `autocfg`

Caused by:
  process didn't exit successfully: `rustc --crate-name autocfg E:\Cargo\registry\src\github.com-1ecc6299db9ec823\autocfg-1.0.1\src\lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off -C metadata=ed90b98a3f642806 -C extra-filename=-ed90b98a3f642806 --out-dir Z:\TEMP\cargo-installBt65NX\release\deps -L dependency=Z:\TEMP\cargo-installBt65NX\release\deps --cap-lints allow` (exit code: 1)

**Comment by crackfan** [comment]
C:\Users\Administrator>rustc --crate-name autocfg E:\Cargo\registry\src\github.com-1ecc6299db9ec823\autocfg-1.0.1\src\lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off -C metadata=ed90b98a3f642806 -C extra-filename=-ed90b98a3f642806 --out-dir Z:\TEMP\cargo-installBt65NX\release\deps -L dependency=Z:\TEMP\cargo-installBt65NX\release\deps --cap-lints allow
{"message":"failed to build archive: function not supported","code":null,"level":"error","spans":[],"children":[],"rendered":"\u001b[0m\u001b[1m\u001b[38;5;9merror\u001b[0m\u001b[0m\u001b[1m\u001b[38;5;15m: failed to build archive: function not supported\u001b[0m\n\n"}
{"message":"aborting due to previous error","code":null,"level":"error","spans":[],"children":[],"rendered":"\u001b[0m\u001b[1m\u001b[38;5;9merror\u001b[0m\u001b[0m\u001b[1m\u001b[38;5;15m: aborting due to previous error\u001b[0m\n\n"}

**Comment by cuviper** [comment]
What's the output of `rustc --version --verbose`?

**Comment by crackfan** [comment]
![image](https://user-images.githubusercontent.com/2922399/129816722-d84fd3e3-ed82-4145-a9cf-476a7189eaf7.png)

**Comment by cuviper** [comment]
Is your `Z:` a network drive? If so, I think this is probably rust-lang/rust#54216, which will hopefully be fixed once Rust upgrades to LLVM 13. You could try setting your temp dir to a local path while you run `cargo install`. If your case is different, then please file a new Rust bug with those details.

Either way, there's nothing `autocfg` can do about it. This crate just happens to be one of the first things that gets compiled in many builds, since it's needed by build scripts.
