### ISSUE TITLE
Backport CARGO_ENCODED_RUSTFLAGS to version 0.1

### ISSUE THREAD

**Issue by tranzystorekk** [cuviper/autocfg#40]
Would it be possible to create a new 0.1 patch release with the CARGO_ENCODED_RUSTFLAGS behavior? Many crates can fail to build on cross-targets with the `--locked` cargo flag on newer rust versions because of the RUSTFLAGS change, noticed in the Void Linux CI: https://github.com/void-linux/void-packages/issues/34889

**Comment by cuviper** [comment]
I did publish 0.1.8 that re-exports from 1.1.0 (or later), as they are actually API compatible. This way the 0.1.x series can pick up newer fixes, but you still have to update the lock file. There's nothing I can do for prior locked versions.

**Comment by tranzystorekk** [comment]
Thank you for the info! I'll close this issue.
