### ISSUE TITLE
Test for specific named feature in std?

### ISSUE THREAD

**Issue by schneems** [cuviper/autocfg#54]
Hello, thanks for the great library. I am wondering if it's possible to test for something like this feature https://doc.rust-lang.org/src/std/path.rs.html#2889

```
    #[stable(feature = "path_try_exists", since = "1.63.0")]
```

I can use the `1.63` version test, but I didn't know if there was a way to be a bit more specific for **why** I'm wanting that version.

**Comment by cuviper** [comment]
I'm not aware of any way that the feature names can be inspected. Apart from writing yourself a comment about the significance of 1.63, the only other thing in `autocfg` is to test something like:

```rust
let ac = autocfg::new();
ac.emit_expression_cfg("Path::new(\"\").try_exists()", "has_path_try_exists");
```

... or a similar `probe_expression` followed by whatever action you choose.

**Comment by schneems** [comment]
Thanks that answers my question. Appreciate the great library!
