### ISSUE TITLE
Getting different crate ids with different host compilers

### ISSUE THREAD

**Issue by NickeZ** [cuviper/autocfg#69]
Hello!

I'm trying to get a firmware to be reproducible with different host compilers. Unfortunately it seems that autocfg affects the crate id, and that then leads to basically all other crate ids also being different and eventually almost all symbols in the binary.

You can check the "Run" step in this job: https://github.com/NickeZ/test-cmetadata/actions/runs/10495122009

The invocations of rustc compiling autocfg ends up being different with:
  * -C metadata=ff7757ee20672155
  * -C metadata=8d956e1242b16064

Both containers run the exact same compiler, 1.81.0-beta.5.

Is this a known problem? Do you know of any workaround?

Regards

**Comment by cuviper** [comment]
> I'm trying to get a firmware to be reproducible with different host compilers. Unfortunately it seems that autocfg affects the crate id, and that then leads to basically all other crate ids also being different and eventually almost all symbols in the binary.

I don't think this is `autocfg` in particular, since we have no influence over that metadata, but build dependencies in general do have that effect. See <https://github.com/rust-lang/cargo/issues/8140>.
